### ISSUE TITLE
No results from push

### ISSUE THREAD

**Issue by keithnet** [drudge/n8n-nodes-tidbyt#1]
Struggling to push to my device.

I can List Installations so I know the API works.

I'm able to render a webp.

The push doesn't seem to achieve anything. My app doesn't show up.

I get no results when I run it manually.

Attached is a slightly censored version of my workflow.
[My_workflow.txt](https://github.com/drudge/n8n-nodes-tidbyt/files/9126641/My_workflow.txt)

**Comment by drudge** [comment]
Hi @keithnet - it's hard to see what the problem might be from this workflow. If you are able to view the binary of the render step and it has a valid webp, there should be no reason the push wouldn't work.

Tidbyt's API doesn't return any value on a successful push, would would return an error if it didn't push to the device successfully.

One thing I noticed is that you have Background set to true, so this wouldn't cause the image to be shown immediately, it would add it to the end of the rotation.

I'm on both the n8n and tidbyt discords if you want to do some interactive debugging.
